ai_providers:
  anthropic:
    api_key_env: ANTHROPIC_API_KEY
    enabled: false
    max_tokens: 4096
    model: claude-3-haiku-20240307
    name: anthropic
    priority: 3
    rate_limit: 1.0
    timeout: 30
  groq:
    api_key_env: GROQ_API_KEY
    enabled: true
    max_tokens: 4096
    model: qwen/qwen3-32b
    name: groq
    priority: 1
    rate_limit: 0.5
    timeout: 30
  local:
    api_key_env: ''
    enabled: false
    max_tokens: 512
    model: microsoft/DialoGPT-medium
    name: local
    priority: 4
    rate_limit: 0.1
    timeout: 60
  openai:
    api_key_env: OPENAI_API_KEY
    enabled: false
    max_tokens: 4096
    model: gpt-4o-mini
    name: openai
    priority: 2
    rate_limit: 1.0
    timeout: 30
config_version: '1.0'
custom_settings: {}
debug: false
log_level: INFO
reporting:
  auto_save: true
  compress_reports: false
  default_format: html
  enable_charts: true
  enable_json: true
  enable_pdf: true
  include_raw_data: false
  output_directory: reports
security:
  allowed_domains: []
  blocked_domains: []
  enable_audit_logging: true
  enable_rate_limiting: true
  max_concurrent_scans: 3
  max_requests_per_hour: 500
  max_requests_per_minute: 30
  require_confirmation: true
  safe_mode: true
sqlmap:
  custom_tamper_scripts: []
  default_level: 1
  default_risk: 1
  default_threads: 5
  default_timeout: 120
  enable_tamper_scripts: true
  max_level: 3
  max_risk: 2
  max_threads: 20
  max_timeout: 600
  timeout_settings:
    initial_scan: 120
    follow_up_scan: 300
    data_extraction: 240
    complex_scan: 480
    adaptive_multiplier: 2.0
    max_adaptive_timeout: 600
ui:
  confirm_dangerous_operations: true
  enable_colors: true
  interactive_mode: false
  progress_indicators: true
  show_banner: true
  verbose_output: false
version: 2.0.0
logging:
  log_directory: logs
  audit_log_file: sqlmap_ai_audit.log
  main_log_file: sqlmap_ai.log
  enable_file_logging: true
  max_log_size_mb: 50
  backup_count: 5
